import Chat from "@/components/Chat";
import Login from "@/components/Login";
import Sidebar from "@/components/Sidebar";
import { useSession } from "next-auth/react";
import Head from "next/head";
// import { api } from "@/utils/api";
export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const session = useSession();

  return (
    <>
      <Head>
        <title>Chat-app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session.data !== null ? (
        <main className="flex h-screen">
          <Sidebar />
          <Chat />
        </main>
      ) : (
        <Login />
      )}
    </>
  );
}
