import Chat from "@/components/Chat";
import Sidebar from "@/components/Sidebar";
import Head from "next/head";
// import { api } from "@/utils/api";
export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Chat-app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen">
        <Sidebar />
        <Chat />
      </main>
    </>
  );
}
